# Generated by Django 4.1.7 on 2023-03-27 22:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poetrypost',
            name='category',
            field=models.CharField(choices=[('PO', 'Poetry'), ('OP', 'Opinion'), ('SS', 'Short Story'), ('PH', 'Photography')], default=django.utils.timezone.now, max_length=2),
            preserve_default=False,
        ),
    ]
