# Generated by Django 4.1.7 on 2023-03-29 04:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_poetrypost_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredimage',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photographypost',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poetrypost',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='poetrypost',
            name='category',
            field=models.CharField(choices=[('Poetry', 'Poetry'), ('Opinion', 'Opinion'), ('Short-Story', 'Short-Story'), ('Photography', 'Photography')], max_length=255),
        ),
    ]
